force_auth = false

credentials = [
    {usr="root", pwd="racine"},
    {usr="bf", pwd="karité"},
    {usr="ci", pwd="cacao"},
    {usr="ma", pwd="olive"},
    {usr="sn", pwd="banane"}
]

usr_projects = [
    {usr="root", projects="*"},
    {usr="bf", projects="bf-co-era5_land;bf-hb-era5_land"},
    {usr="ci", projects="ci-c-era5_land;ci-s-era5_land"},
    {usr="ma", projects="ma-tt-era5_land"},
    {usr="sn", projects="sn-ko-era5_land;sn-se-era5_land;sn-ta-era5_land;sn-study-era5_land,sn-study-enacts"}
]

project_path = [
    {project="context", path="./data/"},             # "gd:1BRtEXOKsp-DWfIm8Wxns_yHmrB7kvfLM"
    {project="bf-co-era5_land", path="./data/"},     # "gd:1i5acNp43NooCL6FewvZaYoVKFaWVFfaA"
    {project="bf-hb-era5_land", path="./data/"},     # "gd:1khYDz9ByfOu16wu8TJUfQbKG4aASKX_y"
    {project="ci-c-era5_land", path="./data/"},      # "gd:15E6dTAXLTdby87MhGiEcd-B1KyBI79nT"
    {project="ci-s-era5_land", path="./data/"},      # "gd:12TMzcJJTd9chZxfFI2qmyGYLGhBENdVj"
    {project="ma-tt-era5_land", path="./data/"},     # "gd:1i1Hdo0yiEpJsaD7R2ZRNhi39gdtwe4MP"
    {project="sn-ko-era5_land", path="./data/"},     # "gd:1tWaZFH9O1wBZz7Whygs0xVDknAa_qjN8"
    {project="sn-se-era5_land", path="./data/"},     # "gd:1PS4tZsCkjUF1Hk7P8z24s5Kum4BraRhf"
    {project="sn-ta-era5_land", path="./data/"},     # "gd:1g8h5hcnZPC--DUdgrTkMeeflmS9us1ES"
    {project="sn-study-era5_land", path="./data/"},  # "gd:1BzwJ-vN-rbB72SDWe3CN0O_nKsgVvXnO"
    {project="sn-study-enacts", path="./data/"}      # "gd:1KxX6EssWMvCi4hAS2JGD-7gyVn3iqX-D"
]

[gd]
json = "gd.json"
client_id = "221296208856-jvk90l4g4ab780v5sufksali2tj27ci6.apps.googleusercontent.com"
client_secret = "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"
refresh_token = "1//04sq9lv1uxZG6CgYIARAAGAQSNwF-L9IrHPfzmsKqZ267z7pnFQ_sdPNwlDeveFehhklQGINi0X8izdtg7GE5k4s51twCbN4_fZM"
auth_url = "https://oauth2.googleapis.com/token"
auth_uri = "https://developers.google.com/oauthplayground"
api_url = "https://www.googleapis.com/drive/v3/files/"
scopes = ["https://www.googleapis.com/auth/drive"]
